# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/ci-build-git?view=azure-devops&tabs=yaml#exclude-or-include-tasks-for-builds-based-on-the-branch-being-built
# https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/slack?view=azure-devops

trigger:
- master
pr:
  autoCancel: true
  branches:
    include:
    - master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install Node Packages'

- script: npm run build
  displayName: 'Build'

- script: npm run test
  displayName: 'Test'

- script: dir

- task: AzureFileCopy@3
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    SourcePath: '$(System.DefaultWorkingDirectory)/dist'
    azureSubscription: 'DevOpsServiceConnection'
    Destination: 'AzureBlob'
    storage: 'stkubcapstone'
    ContainerName: '$web'
