# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install Node Packages'

- script: npm run build
  displayName: 'Build'

- script: npm run test
  displayName: 'Test'

- script: dir

- task: AzureFileCopy@3
  inputs:
    SourcePath: '$(System.DefaultWorkingDirectory)/dist'
    azureSubscription: 'My Connection'
    Destination: 'AzureBlob'
    storage: 'stkubcapstone'
    ContainerName: '$web'
